<img src="logo.png">

# Listas

Las listas en **R** son objetos con una gran flexibilidad. Se trata de *conjuntos ordenados* (es decir, hay un primer elemento, un segundo elemento, etcétera) de una sola dimensión (es decir, tienen longitud) con la particularidad de que sus elementos pueden ser cualquier tipo de objetos; incluso, otras listas.

## Creación de listas

Para crear listas en **R**, utilizamos la función ``list()``. Es muy parecido a crear vectores, pero con la gran diferencia de que los elementos de la lista pueden ser de cualquier tipo.

In [1]:
lista_ejemplo  <- list(1,2,"3")

In [2]:
class(lista_ejemplo)

[1] "list"

In [ ]:
typeof(lista_ejemplo)

Así, puedes pensar que una lista es una caja muy grande donde vas a guardar tus objetos de manera ordenada.

In [4]:
mi_lista  <- list(c(1,2,3),
                 array(data = 1:4, dim = c(2,2)),
                 TRUE)

De manera similar a los vectores, las listas tienen propiedad de nombres. Para accesar a los nombres (o modificarlos) lo podemos hacer desde la creación de la lista o con la función ``names()``.

In [8]:
mi_lista <- list(mi_vector = c(1,2,3),
                 mi_array = array(data = 1:4, dim = c(2,2)),
                 mi_booleano = TRUE)

In [9]:
names(mi_lista)

[1] "mi_vector"   "mi_array"    "mi_booleano"

In [10]:
names(mi_lista)[3] = "mi_logico"

In [11]:
names(mi_lista)

[1] "mi_vector" "mi_array"  "mi_logico"

Es interesante notar que no todos los elementos de las listas deben tener nombre.

In [104]:
lista_nombres <- list(c(1,2,3), letra_a = "a", TRUE )

In [105]:
lista_nombres

[[1]]
[1] 1 2 3

$letra_a
[1] "a"

[[3]]
[1] TRUE

In [106]:
names(lista_nombres)

[1] ""        "letra_a" ""

Como las listas son unidimensionales (aunque puede tener elementos multidimensionales), se les puede aplicar la función ``length()`` para saber cuántos elementos tiene.

In [12]:
length(mi_lista)

[1] 3

También podemos ver su estructura con ``str()``

In [13]:
str(mi_lista)

List of 3
 $ mi_vector: num [1:3] 1 2 3
 $ mi_array : int [1:2, 1:2] 1 2 3 4
 $ mi_logico: logi TRUE


## Indexado de listas

Como las listas son objetos unidimensionales, el indexado solo requiere un parámetro.

Hasta este momento, hemos trabajado con *corchetes simples* para hacer los indexados numéricos. Por ejemplo, ``mi_vector[1]`` me da el valor de la primer posición del objeto ``mi_vector``; ``mi_array[1,3,2]`` de la el elemento de la primer fila, tercer columna y segunda capa del objeto ``mi_array``; ``mi_dataframe[2,3]`` me da el elemento de la segunda fila y tercera columna del objeto ``mi_dataframe``.

En las listas tenemos *dos niveles* de indexado, llamados **nivel del objeto subyacente** y **nivel de lista**.

El nivel del objeto subyacente se refiere al indexado que nos permite **entrar al objeto al cual hace referencia el índice**. Este nivel se especifica con corchetes dobles ``[[  ]]``.

El nivel de lista se refiere al indexado que nos permite **saber qué hay en la posición, a la cual hace referencia el índice, dentro de la lista**. Este nivel se especifica con corchetes simples ``[  ]``.



In [42]:
mi_lista[[2]]

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [36]:
class(mi_lista[[2]])

[1] "matrix"

In [37]:
mi_lista[2]

$mi_array
     [,1] [,2]
[1,]    1    3
[2,]    2    4

In [38]:
class(mi_lista[2])

[1] "list"

Te preguntarás por qué existen dos niveles de indexado en las listas. Esto se debe a que las listas aceptan diferentes tipos de objetos en sus entradas.

De esta manera, por ejemplo, si quieres obtener los elementos 2 y 3 de una lista, entonces estás en el nivel de lista y por lo tanto indexas con corchetes simples: ``mi_lista[c(2,3)]``.

En cambio, si quieres entrar al segundo objeto de una lista por cualquier razón, debes usar doble corchete. Por ejemplo, el segundo elemento de ``mi_lista`` es un array de dos filas y dos columnas, así que para mostrar la segunda fila de este array hacemos ``mi_lista[[2]][2,]``

De hecho, técnicamente ``mi_lista[2]`` vuelve a ser una lista (aquella formada por un solo elemento) en tanto que ``mi_lista[[2]]`` es un array.

Por otra parte, al igual que con los dataframes, podemos utilizar los nombres de los elementos de la lista para accesar a ellos, ya sea con ``[ ]`` para el nivel de listas, o ``[[ ]]`` o con ``$`` para el nivel de objeto subyacente.

In [46]:
mi_lista["mi_vector"]

$mi_vector
[1] 1 2 3

In [47]:
mi_lista[["mi_vector"]]

[1] 1 2 3

In [48]:
mi_lista$mi_vector

[1] 1 2 3

## Modificación de listas

Tomemos la siguiente lista: ``ejemplo_lista  <- list(c("a","b","c"),array(1:10,dim=c(2,5)))``

In [62]:
ejemplo_lista  <- list(c("a","b","c"),array(1:10,dim=c(2,5)))

Para añadir elementos a una lista, utilizamos el nivel de objeto subyacente simplemente indexando por la posición que queremos aumentar.

In [63]:
ejemplo_lista[[5]]  <- c(1,2,3)

In [64]:
ejemplo_lista

[[1]]
[1] "a" "b" "c"

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
NULL

[[4]]
NULL

[[5]]
[1] 1 2 3

Para cambiar todo un elemento de la lista, nuevamente utilizamos el nivel de objeto subyacente

In [65]:
# Cambiar el elemento 5 de la lista ejemplo_lista por un FALSE
ejemplo_lista[[5]] <- TRUE
ejemplo_lista

[[1]]
[1] "a" "b" "c"

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
NULL

[[4]]
NULL

[[5]]
[1] TRUE

## Eliminado de elementos de una lista

El eliminado de elementos de una lista se puede hacer, por ejemplo con ``NULL``. Una de las ventajas de este método es que no hace diferencia entre el uso de ``[ ]``, ``[[ ]]`` y ``$``.

In [78]:
ejemplo_lista  <- list(c("a","b","c"),array(1:10,dim=c(2,5)),TRUE)
ejemplo_lista

[[1]]
[1] "a" "b" "c"

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
[1] TRUE

In [77]:
ejemplo_lista[2] <- NULL
ejemplo_lista

[[1]]
[1] "a" "b" "c"

[[2]]
[1] TRUE

In [79]:
ejemplo_lista[[2]]  <- NULL
ejemplo_lista

[[1]]
[1] "a" "b" "c"

[[2]]
[1] TRUE

In [93]:
mi_lista <- list(mi_vector = c(1,2,3),
                 mi_array = array(data = 1:4, dim = c(2,2)),
                 mi_booleano = TRUE)

In [81]:
mi_lista[["mi_array"]] <- NULL
mi_lista

$mi_vector
[1] 1 2 3

$mi_booleano
[1] TRUE

In [83]:
mi_lista["mi_array"]  <- NULL
mi_lista

$mi_vector
[1] 1 2 3

$mi_booleano
[1] TRUE

In [87]:
mi_lista$mi_array <- NULL
mi_lista

$mi_vector
[1] 1 2 3

$mi_booleano
[1] TRUE

In [91]:
mi_lista[c(1,3)]  <- NULL
mi_lista

In [94]:
mi_lista[-c(1,3)]

$mi_array
     [,1] [,2]
[1,]    1    3
[2,]    2    4

## Combinación de listas

Tomemos dos listas: ``lista1 <- list(c(1,2),"A")`` y ``lista2 <- list(c(10,11),matrix(1:10,nrow=5,ncol=2))``

In [99]:
lista1 <- list(c(1,2),"A")
lista2 <- list("l1" = c(10,11),matrix(1:10,nrow=5,ncol=2))

In [100]:
lista1

[[1]]
[1] 1 2

[[2]]
[1] "A"

In [101]:
lista2

$l1
[1] 10 11

[[2]]
     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

Para combinarlas y obtener una lista de 4 elementos, utilizamos el operador de concatenación: ``c()``

In [107]:
c(lista1,lista2)

[[1]]
[1] 1 2

[[2]]
[1] "A"

$l1
[1] 10 11

[[4]]
     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

In [108]:
class(c(lista1,lista2))

[1] "list"